GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nama": "Angger Fajar",
    "kasus": "Perang sarung di masjid",
    "jenis_kelamin": "lanang"
    
}